/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProRouteImport } from './routes/pro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProIndexRouteImport } from './routes/pro.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProProfileRouteImport } from './routes/pro.profile'
import { Route as ProMissionsRouteImport } from './routes/pro.missions'
import { Route as ProDocumentsRouteImport } from './routes/pro.documents'
import { Route as ProDisposRouteImport } from './routes/pro.dispos'
import { Route as AppProvidersRouteImport } from './routes/app.providers'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAvailabilityRouteImport } from './routes/app.availability'
import { Route as AdminWorkshopsRouteImport } from './routes/admin.workshops'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as AdminCentersRouteImport } from './routes/admin.centers'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdWorkshopsRouteImport } from './routes/projects.$projectId.workshops'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects.$projectId.settings'
import { Route as ProjectsProjectIdSessionsRouteImport } from './routes/projects.$projectId.sessions'
import { Route as ProjectsProjectIdCentersRouteImport } from './routes/projects.$projectId.centers'
import { Route as AppSessionsNewRouteImport } from './routes/app.sessions.new'
import { Route as AppSessionsSessionIdRouteImport } from './routes/app.sessions.$sessionId'
import { Route as AdminProvidersProviderIdDocumentsRouteImport } from './routes/admin.providers.$providerId.documents'
import { Route as AppSessionsSessionIdSeancesNRouteImport } from './routes/app.sessions.$sessionId.seances.$n'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProProfileRoute = ProProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProRoute,
} as any)
const ProMissionsRoute = ProMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => ProRoute,
} as any)
const ProDocumentsRoute = ProDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ProRoute,
} as any)
const ProDisposRoute = ProDisposRouteImport.update({
  id: '/dispos',
  path: '/dispos',
  getParentRoute: () => ProRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAvailabilityRoute = AppAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AppRoute,
} as any)
const AdminWorkshopsRoute = AdminWorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCentersRoute = AdminCentersRouteImport.update({
  id: '/centers',
  path: '/centers',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdWorkshopsRoute =
  ProjectsProjectIdWorkshopsRouteImport.update({
    id: '/workshops',
    path: '/workshops',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSessionsRoute =
  ProjectsProjectIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCentersRoute =
  ProjectsProjectIdCentersRouteImport.update({
    id: '/centers',
    path: '/centers',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const AppSessionsNewRoute = AppSessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AdminProvidersProviderIdDocumentsRoute =
  AdminProvidersProviderIdDocumentsRouteImport.update({
    id: '/$providerId/documents',
    path: '/$providerId/documents',
    getParentRoute: () => AdminProvidersRoute,
  } as any)
const AppSessionsSessionIdSeancesNRoute =
  AppSessionsSessionIdSeancesNRouteImport.update({
    id: '/seances/$n',
    path: '/seances/$n',
    getParentRoute: () => AppSessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pro': typeof ProRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/centers': typeof AdminCentersRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/providers': typeof AdminProvidersRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/workshops': typeof AdminWorkshopsRoute
  '/app/availability': typeof AppAvailabilityRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/providers': typeof AppProvidersRoute
  '/pro/dispos': typeof ProDisposRoute
  '/pro/documents': typeof ProDocumentsRoute
  '/pro/missions': typeof ProMissionsRoute
  '/pro/profile': typeof ProProfileRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/pro/': typeof ProIndexRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRouteWithChildren
  '/app/sessions/new': typeof AppSessionsNewRoute
  '/projects/$projectId/centers': typeof ProjectsProjectIdCentersRoute
  '/projects/$projectId/sessions': typeof ProjectsProjectIdSessionsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/workshops': typeof ProjectsProjectIdWorkshopsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/admin/providers/$providerId/documents': typeof AdminProvidersProviderIdDocumentsRoute
  '/app/sessions/$sessionId/seances/$n': typeof AppSessionsSessionIdSeancesNRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/centers': typeof AdminCentersRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/providers': typeof AdminProvidersRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/workshops': typeof AdminWorkshopsRoute
  '/app/availability': typeof AppAvailabilityRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/providers': typeof AppProvidersRoute
  '/pro/dispos': typeof ProDisposRoute
  '/pro/documents': typeof ProDocumentsRoute
  '/pro/missions': typeof ProMissionsRoute
  '/pro/profile': typeof ProProfileRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/pro': typeof ProIndexRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRouteWithChildren
  '/app/sessions/new': typeof AppSessionsNewRoute
  '/projects/$projectId/centers': typeof ProjectsProjectIdCentersRoute
  '/projects/$projectId/sessions': typeof ProjectsProjectIdSessionsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/workshops': typeof ProjectsProjectIdWorkshopsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/admin/providers/$providerId/documents': typeof AdminProvidersProviderIdDocumentsRoute
  '/app/sessions/$sessionId/seances/$n': typeof AppSessionsSessionIdSeancesNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pro': typeof ProRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/centers': typeof AdminCentersRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/providers': typeof AdminProvidersRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/workshops': typeof AdminWorkshopsRoute
  '/app/availability': typeof AppAvailabilityRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/providers': typeof AppProvidersRoute
  '/pro/dispos': typeof ProDisposRoute
  '/pro/documents': typeof ProDocumentsRoute
  '/pro/missions': typeof ProMissionsRoute
  '/pro/profile': typeof ProProfileRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/pro/': typeof ProIndexRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRouteWithChildren
  '/app/sessions/new': typeof AppSessionsNewRoute
  '/projects/$projectId/centers': typeof ProjectsProjectIdCentersRoute
  '/projects/$projectId/sessions': typeof ProjectsProjectIdSessionsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/workshops': typeof ProjectsProjectIdWorkshopsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/admin/providers/$providerId/documents': typeof AdminProvidersProviderIdDocumentsRoute
  '/app/sessions/$sessionId/seances/$n': typeof AppSessionsSessionIdSeancesNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/pro'
    | '/signup'
    | '/admin/centers'
    | '/admin/export'
    | '/admin/projects'
    | '/admin/providers'
    | '/admin/users'
    | '/admin/workshops'
    | '/app/availability'
    | '/app/calendar'
    | '/app/providers'
    | '/pro/dispos'
    | '/pro/documents'
    | '/pro/missions'
    | '/pro/profile'
    | '/projects/$projectId'
    | '/admin/'
    | '/app/'
    | '/pro/'
    | '/app/sessions/$sessionId'
    | '/app/sessions/new'
    | '/projects/$projectId/centers'
    | '/projects/$projectId/sessions'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/workshops'
    | '/projects/$projectId/'
    | '/admin/providers/$providerId/documents'
    | '/app/sessions/$sessionId/seances/$n'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/admin/centers'
    | '/admin/export'
    | '/admin/projects'
    | '/admin/providers'
    | '/admin/users'
    | '/admin/workshops'
    | '/app/availability'
    | '/app/calendar'
    | '/app/providers'
    | '/pro/dispos'
    | '/pro/documents'
    | '/pro/missions'
    | '/pro/profile'
    | '/admin'
    | '/app'
    | '/pro'
    | '/app/sessions/$sessionId'
    | '/app/sessions/new'
    | '/projects/$projectId/centers'
    | '/projects/$projectId/sessions'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/workshops'
    | '/projects/$projectId'
    | '/admin/providers/$providerId/documents'
    | '/app/sessions/$sessionId/seances/$n'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/pro'
    | '/signup'
    | '/admin/centers'
    | '/admin/export'
    | '/admin/projects'
    | '/admin/providers'
    | '/admin/users'
    | '/admin/workshops'
    | '/app/availability'
    | '/app/calendar'
    | '/app/providers'
    | '/pro/dispos'
    | '/pro/documents'
    | '/pro/missions'
    | '/pro/profile'
    | '/projects/$projectId'
    | '/admin/'
    | '/app/'
    | '/pro/'
    | '/app/sessions/$sessionId'
    | '/app/sessions/new'
    | '/projects/$projectId/centers'
    | '/projects/$projectId/sessions'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/workshops'
    | '/projects/$projectId/'
    | '/admin/providers/$providerId/documents'
    | '/app/sessions/$sessionId/seances/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProRoute: typeof ProRouteWithChildren
  SignupRoute: typeof SignupRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof ProRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/profile': {
      id: '/pro/profile'
      path: '/profile'
      fullPath: '/pro/profile'
      preLoaderRoute: typeof ProProfileRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/missions': {
      id: '/pro/missions'
      path: '/missions'
      fullPath: '/pro/missions'
      preLoaderRoute: typeof ProMissionsRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/documents': {
      id: '/pro/documents'
      path: '/documents'
      fullPath: '/pro/documents'
      preLoaderRoute: typeof ProDocumentsRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/dispos': {
      id: '/pro/dispos'
      path: '/dispos'
      fullPath: '/pro/dispos'
      preLoaderRoute: typeof ProDisposRouteImport
      parentRoute: typeof ProRoute
    }
    '/app/providers': {
      id: '/app/providers'
      path: '/providers'
      fullPath: '/app/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/availability': {
      id: '/app/availability'
      path: '/availability'
      fullPath: '/app/availability'
      preLoaderRoute: typeof AppAvailabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/workshops': {
      id: '/admin/workshops'
      path: '/workshops'
      fullPath: '/admin/workshops'
      preLoaderRoute: typeof AdminWorkshopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/centers': {
      id: '/admin/centers'
      path: '/centers'
      fullPath: '/admin/centers'
      preLoaderRoute: typeof AdminCentersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/workshops': {
      id: '/projects/$projectId/workshops'
      path: '/workshops'
      fullPath: '/projects/$projectId/workshops'
      preLoaderRoute: typeof ProjectsProjectIdWorkshopsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/sessions': {
      id: '/projects/$projectId/sessions'
      path: '/sessions'
      fullPath: '/projects/$projectId/sessions'
      preLoaderRoute: typeof ProjectsProjectIdSessionsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/centers': {
      id: '/projects/$projectId/centers'
      path: '/centers'
      fullPath: '/projects/$projectId/centers'
      preLoaderRoute: typeof ProjectsProjectIdCentersRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/app/sessions/new': {
      id: '/app/sessions/new'
      path: '/sessions/new'
      fullPath: '/app/sessions/new'
      preLoaderRoute: typeof AppSessionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessions/$sessionId': {
      id: '/app/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/app/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/providers/$providerId/documents': {
      id: '/admin/providers/$providerId/documents'
      path: '/$providerId/documents'
      fullPath: '/admin/providers/$providerId/documents'
      preLoaderRoute: typeof AdminProvidersProviderIdDocumentsRouteImport
      parentRoute: typeof AdminProvidersRoute
    }
    '/app/sessions/$sessionId/seances/$n': {
      id: '/app/sessions/$sessionId/seances/$n'
      path: '/seances/$n'
      fullPath: '/app/sessions/$sessionId/seances/$n'
      preLoaderRoute: typeof AppSessionsSessionIdSeancesNRouteImport
      parentRoute: typeof AppSessionsSessionIdRoute
    }
  }
}

interface AdminProvidersRouteChildren {
  AdminProvidersProviderIdDocumentsRoute: typeof AdminProvidersProviderIdDocumentsRoute
}

const AdminProvidersRouteChildren: AdminProvidersRouteChildren = {
  AdminProvidersProviderIdDocumentsRoute:
    AdminProvidersProviderIdDocumentsRoute,
}

const AdminProvidersRouteWithChildren = AdminProvidersRoute._addFileChildren(
  AdminProvidersRouteChildren,
)

interface AdminRouteChildren {
  AdminCentersRoute: typeof AdminCentersRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminProvidersRoute: typeof AdminProvidersRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkshopsRoute: typeof AdminWorkshopsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCentersRoute: AdminCentersRoute,
  AdminExportRoute: AdminExportRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminProvidersRoute: AdminProvidersRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkshopsRoute: AdminWorkshopsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppSessionsSessionIdRouteChildren {
  AppSessionsSessionIdSeancesNRoute: typeof AppSessionsSessionIdSeancesNRoute
}

const AppSessionsSessionIdRouteChildren: AppSessionsSessionIdRouteChildren = {
  AppSessionsSessionIdSeancesNRoute: AppSessionsSessionIdSeancesNRoute,
}

const AppSessionsSessionIdRouteWithChildren =
  AppSessionsSessionIdRoute._addFileChildren(AppSessionsSessionIdRouteChildren)

interface AppRouteChildren {
  AppAvailabilityRoute: typeof AppAvailabilityRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppProvidersRoute: typeof AppProvidersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRouteWithChildren
  AppSessionsNewRoute: typeof AppSessionsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvailabilityRoute: AppAvailabilityRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppProvidersRoute: AppProvidersRoute,
  AppIndexRoute: AppIndexRoute,
  AppSessionsSessionIdRoute: AppSessionsSessionIdRouteWithChildren,
  AppSessionsNewRoute: AppSessionsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ProRouteChildren {
  ProDisposRoute: typeof ProDisposRoute
  ProDocumentsRoute: typeof ProDocumentsRoute
  ProMissionsRoute: typeof ProMissionsRoute
  ProProfileRoute: typeof ProProfileRoute
  ProIndexRoute: typeof ProIndexRoute
}

const ProRouteChildren: ProRouteChildren = {
  ProDisposRoute: ProDisposRoute,
  ProDocumentsRoute: ProDocumentsRoute,
  ProMissionsRoute: ProMissionsRoute,
  ProProfileRoute: ProProfileRoute,
  ProIndexRoute: ProIndexRoute,
}

const ProRouteWithChildren = ProRoute._addFileChildren(ProRouteChildren)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdCentersRoute: typeof ProjectsProjectIdCentersRoute
  ProjectsProjectIdSessionsRoute: typeof ProjectsProjectIdSessionsRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdWorkshopsRoute: typeof ProjectsProjectIdWorkshopsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdCentersRoute: ProjectsProjectIdCentersRoute,
  ProjectsProjectIdSessionsRoute: ProjectsProjectIdSessionsRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdWorkshopsRoute: ProjectsProjectIdWorkshopsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProRoute: ProRouteWithChildren,
  SignupRoute: SignupRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
