/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProRouteImport } from './routes/pro'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProvidersRouteImport } from './routes/app.providers'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppSessionsNewRouteImport } from './routes/app.sessions.new'
import { Route as AppSessionsSessionIdRouteImport } from './routes/app.sessions.$sessionId'
import { Route as AppSessionsSessionIdSeancesNRouteImport } from './routes/app.sessions.$sessionId.seances.$n'

const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsNewRoute = AppSessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsSessionIdSeancesNRoute =
  AppSessionsSessionIdSeancesNRouteImport.update({
    id: '/seances/$n',
    path: '/seances/$n',
    getParentRoute: () => AppSessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/pro': typeof ProRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/': typeof AppIndexRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRouteWithChildren
  '/app/sessions/new': typeof AppSessionsNewRoute
  '/app/sessions/$sessionId/seances/$n': typeof AppSessionsSessionIdSeancesNRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/pro': typeof ProRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/providers': typeof AppProvidersRoute
  '/app': typeof AppIndexRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRouteWithChildren
  '/app/sessions/new': typeof AppSessionsNewRoute
  '/app/sessions/$sessionId/seances/$n': typeof AppSessionsSessionIdSeancesNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/pro': typeof ProRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/': typeof AppIndexRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRouteWithChildren
  '/app/sessions/new': typeof AppSessionsNewRoute
  '/app/sessions/$sessionId/seances/$n': typeof AppSessionsSessionIdSeancesNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/pro'
    | '/app/calendar'
    | '/app/providers'
    | '/app/'
    | '/app/sessions/$sessionId'
    | '/app/sessions/new'
    | '/app/sessions/$sessionId/seances/$n'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/pro'
    | '/app/calendar'
    | '/app/providers'
    | '/app'
    | '/app/sessions/$sessionId'
    | '/app/sessions/new'
    | '/app/sessions/$sessionId/seances/$n'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/pro'
    | '/app/calendar'
    | '/app/providers'
    | '/app/'
    | '/app/sessions/$sessionId'
    | '/app/sessions/new'
    | '/app/sessions/$sessionId/seances/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  ProRoute: typeof ProRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/providers': {
      id: '/app/providers'
      path: '/providers'
      fullPath: '/app/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessions/new': {
      id: '/app/sessions/new'
      path: '/sessions/new'
      fullPath: '/app/sessions/new'
      preLoaderRoute: typeof AppSessionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessions/$sessionId': {
      id: '/app/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/app/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessions/$sessionId/seances/$n': {
      id: '/app/sessions/$sessionId/seances/$n'
      path: '/seances/$n'
      fullPath: '/app/sessions/$sessionId/seances/$n'
      preLoaderRoute: typeof AppSessionsSessionIdSeancesNRouteImport
      parentRoute: typeof AppSessionsSessionIdRoute
    }
  }
}

interface AppSessionsSessionIdRouteChildren {
  AppSessionsSessionIdSeancesNRoute: typeof AppSessionsSessionIdSeancesNRoute
}

const AppSessionsSessionIdRouteChildren: AppSessionsSessionIdRouteChildren = {
  AppSessionsSessionIdSeancesNRoute: AppSessionsSessionIdSeancesNRoute,
}

const AppSessionsSessionIdRouteWithChildren =
  AppSessionsSessionIdRoute._addFileChildren(AppSessionsSessionIdRouteChildren)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppProvidersRoute: typeof AppProvidersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRouteWithChildren
  AppSessionsNewRoute: typeof AppSessionsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppProvidersRoute: AppProvidersRoute,
  AppIndexRoute: AppIndexRoute,
  AppSessionsSessionIdRoute: AppSessionsSessionIdRouteWithChildren,
  AppSessionsNewRoute: AppSessionsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  ProRoute: ProRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
